### ISSUE TITLE
Sample data not available through pip installation

### ISSUE THREAD

**Issue by sebgoti** [sylvainprigent/stracking#1]
I get this error when trying to load the 'fake_tracks1()' dataset:

FileExistsError: [Errno Cannot find the file:] /Users/segonzal/opt/anaconda3/envs/stracking/lib/python3.9/site-packages/stracking/data/fake_tracks1.tif

**Comment by sylvainprigent** [comment]
I released the version v0.1.6 that includes the data files in the package using pip install
